---

- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False

  tasks:
    - name: sandbox ec2 group
      ec2_group:
        name: sandbox_sg
        description: sanbox ec2 security group
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: Launch instance
      ec2:
         key_name: "{{ ssh_key }}"
         group: sandbox_sg
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ vpcsubnet }}"
         assign_public_ip: yes
      register: ec2
    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- name: This will configure the new instance by installing the software it needs
  hosts: launched
  sudo: True
  gather_facts: True
  roles:
    - apache

- name: test infrastructure components
  hosts: localhost
  gather_facts: false

  tasks:
    - name: get the url of the new web server to validate is up
      action: uri url=http://{{ item.public_dns_name }}/ return_content=yes
      register: webpage
      with_items: ec2.instances
      failed_when: "'Welcome' not in webpage.content"
