---
# tasks file for apache

- name: install apache
  yum: name=httpd state=latest

- name: start the apache service
  service: name=httpd state=started

- name: template index file for web server
  template: src=index.html.j2 dest=/var/www/html/index.html
